import React from 'react';

const TermsandCondition = () => {
  return (
    <div className="bg-gray-900 min-h-screen text-white py-12 px-4">
      <div className="max-w-6xl mx-auto bg-gray-800/60 rounded-lg p-8 border border-gray-700/50 shadow-lg">
        <h1 className="text-3xl font-bold mb-6 text-blue-400 border-b border-gray-700 pb-4">
          Capvalis Terms and Conditions
        </h1>

        <div className="space-y-6 text-gray-300 text-sm">
          {/* Section 1 */}
          <section>
         <h2 className="text-xl font-semibold mb-3 text-green-400"> Trade Name and Legal Entity</h2>
          Capvalis.com operates under the trade name “CapValis”, which is used for branding and commercial purposes. The legal entity registered for this business is Abhiv Consultancy LLP. All contracts, agreements, and legal obligations entered into on behalf of CapValis are executed in the name of Abhiv Consultancy LLP.
          </section>
          <section>
            <h2 className="text-xl font-semibold mb-3 text-green-400">1. Terms and Conditions</h2>
            <p>1.1 These Terms & Conditions are legally binding between the person accessing the website or downloading the app (which expression shall include its successors and assigns).</p>
            <p>1.2 By accessing this website or downloading this application you shall be giving your consent to defined terms & conditions & will be bound by existing Information technology Act 2000/2008 & Rules defined and other law as applicable in India.</p>
            <p>1.3 Acceptance of the General Terms and Conditions and Privacy Policy is mandatory in order to use the services provided by us. The use of services provided by us implies/denotes full acceptance of the General Terms and Conditions and privacy policy.</p>
            <p>1.4 These Terms constitute an 'electronic record' within the meaning of the applicable law (including the Information Technology Act, 2000, IT Act 2008 Amendment) and is generated by a computer system and does not require any physical or digital signatures.</p>
            <p>1.5 The word ‘webinar’ is a blend of ‘web’ and ‘seminar’ ‘online training’. A webinar is an event held on the internet which is attended exclusively by an online audience. This distinguishes it from a webcast, which also includes the presence of a physical audience. Other terms used as alternatives for webinars are web events, online seminars, webcasts, web lectures/conferences, and virtual events.</p>
          </section>

          {/* Section 2 */}
          <section>
            <h2 className="text-xl font-semibold mb-3 text-green-400">2. Definitions</h2>
            <p>2.1 Organization means Capvalis, the Organization of events.</p>
            <p>2.2 Application Form is an online or printed participation order form provided by the organization.</p>
            <p>2.3 Client/User refers to any person, firm, or organization participating in events/training organized by the organization.</p>
            <p>2.4 Event/Training means any teaching or conference organized by the Organization in which the Client/User participates. Venue means the venue/place in which the Event is taking place.</p>
            <p>2.5 Speakers are individuals providing training or speaking at events.</p>
            <p>2.6 VC means Virtual Conference.</p>
            <p>2.7 Webinar refers to a conference held over the Internet.</p>
            <p>2.8 The service provided by Capvalis includes training participants on stock market vulnerabilities and opportunities.</p>
            <p>2.9 User - states any person who has attained majority under Indian Law and any other country law, who has registered with thewebsite or downloaded the application on mobile in order to utilize the services provided by Capvalis.</p>
            Please read these Terms carefully before you use the Application or any Service offered by Capvalisthrough the Application. These terms control the relationship between Capvalisand you. They do not create any third-party beneficiary rights.
          </section>

          {/* Section 3 */}
          <section>
            <h2 className="text-xl font-semibold mb-3 text-green-400">3. Registration</h2>
            <p>3.1 By registering & using Capvalis application, the user is bound to provide true, and accurate information, as sought at the time of signing and from time to time where it is required. Capvalis does not verify or controls the accuracy of the information provided by the users.</p>
            <p>3.2 In case of non-compliance of any of the terms and conditions by any user, Capvalis reserves right, to withdraw the account of the user and discontinue all services for that user without any notice.</p>
            <p>3.3 Capvalis reserves the right to verify the information provided by its Users, if Capvalis notices any given information by the user is not correct, then the user agrees to provide Capvalis, additional information or documents when requested to establish the authenticity of their account. If an account is found to be fake, not genuine, or duplicate, Capvalis reserves the right delete such account without any notice/ warning or the like.</p>
            <p>3.4 Capvalis is not requesting any personal password or other information that is not relevant and will not be responsible for any consequences resulting from a User sharing his/her personal password of the account with third parties. In the above event, it will be the User who will be held responsible for such negligence.</p>
          </section>

          {/* Section 4 */}
          <section>
            <h2 className="text-xl font-semibold mb-3 text-green-400">4. Training/Event</h2>
            <p>4.1 Capvalis will organize online/offline training sessions and events users can avail Services made available to you by Capvalis through the Training / Event. Capvalis may at its discretion allow you to use some of these services free of charge. Our Services are very diverse and additional terms or product requirements may apply to certain Services. These additional terms are made a part of these Terms by this reference. If there is a conflict between these terms and the additional terms, the additional terms will supersede these terms.</p>
            <p>4.2 Services shall include, but not be limited to, Training/Event more information about the Services is available on Capvalis website at Capvalis.com ("Web Site").</p>
            <p>4.3 Online Virtual training/event may be held and the user agrees his/her participation for the same.</p>
          </section>

          {/* Section 5 */}
          <section>
            <h2 className="text-xl font-semibold mb-3 text-green-400">5. Your Access to Web Site/Application/Online Event</h2>
            <p>5.1 We will endeavour to ensure error-free availability of the Website/Application or Services or contents thereof to you, however, your access to the Application may occasionally be suspended or restricted for upgrades, maintenance, or updating the website/application at any time without prior notice. We will try to limit the frequency and duration of any such suspension or restriction.You are responsible for any charges incurred with your internet service provider that you may incur by accessing the Application or Services made available through the Application, including text messaging and data charges. If you're unsure what those charges may be, you should ask your service provider before using the Application or the Services.</p>
            <p>5.2 You must not use the website/application or the Services rendered by Capvalis for fraudulent purposes or in connection with a criminal offence or other unlawful activity or to send, post, share, use or reuse any material that does not belong to you or that you are not authorized to send; or is illegal, offensive (including but not limited to material that is sexually explicit content or which promotes racism, bigotry, hatred or physical harm), deceptive, misleading, abusive, indecent, harassing, blasphemous, defamatory, libelous, obscene, pornographic, pedophilic or menacing; ethnically objectionable, disparaging or in breach of copyright, trademark, confidentiality, privacy or any other proprietary information or right; or is otherwise injurious to third parties; or relates to or promotes money laundering or gambling; or is harmful to minors in any way; or impersonates another person; or threatens the unity, integrity, security or sovereignty of India or friendly relations with foreign States; or objectionable or otherwise unlawful in any manner whatsoever; or which consists of or contains software viruses, political campaigning, commercial solicitation, chain letters, mass mailings or any spam to cause annoyance, inconvenience or needless anxiety.</p>
            <p>5.3 Online conference/event takes place virtually over Internet Capvalis may choose to usetools such ZOOM, WEBEX, MICROSOFT TEAMS, GOOGLE MEET or any other third party platform which may be paid, free, or trial version, Client/User hereby agrees to adhere to terms and conditions of third party tool for any damage.<br /><br />Internet access (fees may apply), and certain software (fees may apply), and may require obtaining updates or upgrades from time to time. Because use of the Services involves hardware, software, and Internet access, your ability to access and use the Services may be affected by the performance of these factors. High-speed Internet access is recommended. You acknowledge and agree that such system requirements, which may be changed from time to time, are your responsibility.</p>
            <p>5.4 A participant who is part of online/offline training/event will not record any of the training in part or whole and use that to circulate free of cost or paid, session delivered by Capvalis is copyrighted to the organization.</p>
          </section>

          {/* Section 6 */}
          <section>
            <h2 className="text-xl font-semibold mb-3 text-green-400">
              6. Order Terms and Conditions
            </h2>
            <h3 className="text-lg font-semibold mb-2 text-blue-400">6.1 Definitions</h3>
            <p>6.1.1 "Order" means Capvalis’s Order process, which is subject to acceptance of these Terms and Conditions.</p>
            <p>6.1.2 "Client/User" means the person/s, firm, or company making an Order.</p>
            <p>6.1.3 "Training/Event" means the training/event or events which are the subject of the session booked for.</p>
            <p>6.1.4 "Capvalis" means the training/event organizing company.</p>
            <p>6.1.5 "Quotation" means the price defined for various courses by Capvalis to the Client/User, which is the subject of the Order.</p>
            <p>6.1.6 "Services" means the training/event services to be performed by Capvalis pursuant to the Order in accordance with these Terms.</p>
            <p>6.1.7 "Terms" means these Order terms and conditions.</p>
            <p>6.1.8 "Offline Training/Event" means any individual who receives the training in a physically closed venue.</p>
            <p>6.1.9 “Online Training/Event” means a conference held via webinar.</p>

          {/* Section 6.2 */}
          <h3 className="text-lg font-semibold mb-2 text-blue-400">6.2 Order and Payment Terms</h3>
          <p>6.2.1 All prices stated by Capvalis in a Quotation are exclusive of any tax which is applicable, and the Client/User shall be additionally liable to pay Capvalis.</p>
          <p>6.2.2 Upon receipt of the Order from the Client/User, a legally binding contract shall be formed for registration.</p>
          <p>6.2.3 Confirmation of participation in the Training/Event will be after signing and submitting payment to Capvalis/Organization.</p>
          <p>6.2.4 The Client/User shall pay to Capvalis the full amount set out in the Quotation before the Training/Event.</p>
          <p>6.2.5 Any items stated in the Quotation as "additional" items or any items requested by the Client/User after the Order has been confirmed by Capvalis must be confirmed by the Client/User in writing (email shall be sufficient) before being actioned by Capvalis.</p>
          <p>6.2.6 Time for payment shall be of the essence. If the Client/User fails to make any payment before the Training/Event, Capvalis shall be entitled (at its discretion) to cancel the Order by notice in writing to the Client/User.</p>
          <p>6.2.7 Any variation or amendment to these payment terms will be set out by Capvalis in writing on the Order.</p>
          <p>6.2.8 Any typographical, clerical, or other error or omission in any Quotation, correspondence, or other Order documents or information issued by Capvalis shall be subject to correction without any liability whatsoever on the part of Capvalis.</p>

          {/* Section 6.3 */}
          <h3 className="text-lg font-semibold mb-2 text-blue-400">6.3. VARIATION AND CANCELLATION</h3>
          <p>6.3.1 If the Client/User wishes to vary any details of the Order after it is returned to Capvalis, it shall notify Capvalis in writing as soon as possible. Capvalis shall endeavour to make any required changes, but any additional costs thereby incurred shall be invoiced to the Client/User.</p>
          <p>6.3.2 Whilst every reasonable effort will be made to ensure that the Services are provided in accordance with the Order, Capvalis reserves the right in its sole and absolute discretion to make any changes to the Services for the Event which do not in the opinion of CAPVALIS materially affect the quality of the Services. If CAPVALIS has to make any material changes relating to the Order it shall notify the Client/User forthwith Capvalis shall endeavour to keep such changes to a minimum and shall seek to offer the Client/User arrangements as close to the original as is reasonably possible in the circumstances. Where such alternative is not acceptable to the Client/User acting reasonably and in good faith, CAPVALIS shall refund to the Client/User the price paid according to the Order</p>
          <p>6.3.3 Capvalis/Organization holds the right to modify the Training/event duration, change of speakers, venue, titles, dates, opening hours or cancel the Training/event completely without any compensation to the Client/User.</p>
          <p>6.3.4 Capvalis/Organization does not warrant the success of the Training/event nor guarantees if the Client/User will benefit from participating in the Training/event and the Client/User agrees to hold the Organization harmless in the event the Training/event does not meet its expectations For any reason If the Training/event is postponed, it will be informed to you and the payment made by you will be credited towards the rescheduled date. If you are unable to attend the rescheduled event, you will receive a 100% credit representing payment made towards a future Training/event of Capvalis/ Organization Cancellation of an Order will not be accepted by CAPVALIS if the Client/User has availed services from the organization or in any circumstance if the client/user is not able to participate/attend Training/event imparted by Organization.</p>
          <p>6.3.5 If for any reason beyond the reasonable control of Capvalis(including but not limited to an Act of God, explosion, abnormally inclement weather, flood, tempest, fire or accident, war or threat of war, terrorist activity or threat of terrorism, sabotage, insurrection, civil disturbance or requisition, regulations, bye-laws, prohibitions or measures of any kind on the part of any governmental or local authority, import or export regulations or embargoes, strikes, lockouts or other industrial actions or trade disputes, power failure), the Event and/or the Services are cancelled or disrupted in any way, Capvalis shall not be liable to the Client/User or be deemed to be in breach of the Order or these Terms by reason of any delay in performing, or failure to perform any of its obligations in relation to the Order or these Terms. Capvalis may choose to, but shall not be obliged to, agree in good faith with the Client/User the amount of any refund to the Client/User. If the Client/User wishes to protect its investment in the Services purchased in relation to the Event, the Client/User is advised to seek contingency insurance from a specialist contingency insurance broker. Capvalis shall have no further liability to the Client/User arising from Capvalis’s failure to perform the Services in any such circumstances.</p>
          <p>6.3.6 Client/User is responsible for the safety and security of devices used like mobile, tablet, laptop, desktop, or any other device used during the conference, Client/User will have antivirus, firewall, and other security measures which are required and during the conference, there may be additional cost/fee for internet usage, electricity, etc… which will be borne by Client/User, Organization will not be responsible for any damage to the system used by Client/User.</p>
        </section>

        {/* Section 7 */}
        <section>
          <h2 className="text-xl font-semibold mb-3 text-green-400">7. LIMITATION</h2>
          <p>7.1 Capvalis shall not under any circumstances be liable to the Client/User in contract, tort (including negligence) or otherwise for loss of revenues or opportunities, goodwill, reputation, or any type of special, indirect, or consequential loss (even if such loss was reasonably foreseeable or Capvalis had been advised of the possibility of the Client/User incurring the same).</p>
          <p>7.2 Further, Capvalis shall have no liability for any death or bodily injury (except death or injury caused by the negligence of Capvalis, its staff or contractors), or loss of or damage to property, of anyone attending the Training/Event pursuant to the Order, whether arising from such attendance, or in relation to the provision or use of the facilities at the Event. The Client/User agrees to indemnify Capvalis against any claim in respect of any such liability (and the costs and expenses incurred by Capvalis in relation thereto).</p>
          <p>7.3 Without prejudice to any other limitation or exclusion of liability set out in these Terms and to the fullest extent permitted by law, the total liability of Capvalis to the Client/User in contract, tort or otherwise including negligence (save for any liability arising from death or personal injury due to the negligence of CAPVALIS or its employees which shall be unlimited) arising in relation to the Event (and/or the provision of the Services to the Client/User) shall not exceed 10% of the total amount paid by the Client/User hereunder.</p>
          <p>7.4 Capvalis will have no liability for viruses, data, databases, existing in the Client/User system during the conference.</p>
        </section>

        {/* Section 7 */}
        <section>
          <h2 className="text-xl font-semibold mb-3 text-green-400">
            GENERAL
          </h2>
          <p>7.4.1 All Quotations are made and orders accepted subject to these Terms. These Terms shall apply to all Quotations and Orders in precedence over any other printed terms and conditions, including any appearing on the Client/User's stationery or correspondence.</p>
          <p>7.4.2 The Client/User shall procure that all Orders comply with these Terms and furthermore the Client/User indemnifies Capvalis against all claims, costs, damages, and judgments awarded against or incurred or paid by CAPVALIS as a result of or in connection with a claim made by an Order.</p>
          <p>7.4.3 Capvalis will conduct only the Training / Event if your participation in the Training/Event requires to travel from within the country to other city or traveling from abroad, all the travel expense, lodging, and all required modalities, including the issuance of a visa for the country where the event is held, are your own responsibility.</p>
          <p>7.4.5 No amendment or variation to these Terms shall be binding unless agreed in writing by both parties.</p>
          <p>7.4.6 The Client/User consents to being photographed at the Event (physically/virtually, to filming and sound recording of the Event and consents to the use of such, photographs and/or recordings in any marketing or promotional materials in connection with the Event, on the Event website and in any broadcast or publication in any territory in the world.</p>
          <p>7.4.7 No binding contract shall be formed until Capvalis has received acceptance from the Client/User of the Order (which incorporates these Terms) and confirmation of the Order shall be subject to Capvalis receiving payment in full in accordance with clause 3.</p>
          <p>7.4.8 No waiver by Capvalis of any breach of these Terms by the Client/User shall be considered as a waiver of any subsequent breach of the same or any other provision.</p>
          <p>7.4.9 If any provision of these Terms is held by any competent authority to be invalid or unenforceable in whole or in part the validity of the other provisions of these Terms and the remainder of the provision in question shall not be affected thereby.</p>
          <p>7.4.11 The rights granted to the Client/User hereunder are personal to the Client/User and may not be transferred or assigned to any third party without the prior written consent of Capvalis</p>
          <p>7.4.12 The Quotation, the Order, and these Terms contain the entire understanding between the parties with respect to their agreement concerning the Training/Event. By entering into this contract neither party has relied on (nor shall it have any remedy, in contract or tort, in respect of) any statement, representation, warranty, or understanding which is not expressly set out in the Quotation, Order or these Terms, provided that nothing herein shall operate to exclude or limit any liability for fraud.</p>
          <p>7.4.13 The Client/User shall at all times be subject to the terms, conditions, and rules imposed by the organizers of the event and/or the Event venue and shall indemnify CAPVALIS from and against all and any claims arising from the Client/User’s breach of the same.</p>
          <p>7.4.14 The Client/User shall not sell the benefit of any Order on the wholesale or trade market without prior written consent from Capvalis. No Client/User or Ticket Holder may transfer the benefit of the Order for use as a competition prize or other promotional use.</p>
          <p>7.4.15 Online webinar may be held using tools such as ZOOM, WEBEX, MICROSOFT TEAMS, GOOGLE MEET or any other third party platform which may be paid, free, or trial version, Client/User hereby agrees to adhere to terms and conditions of third party tool for any damage. Events conducted and these tools may not be ERROR-FREE, Capvalis will not have any liability towards downtime, ERROR, etc. Client/User should go through the Terms and Conditions and Privacy policy of such vendors used.</p>
        </section>

        {/* Section 8 */}
        <section>
            <h2 className="text-xl font-semibold mb-3 text-green-400">8. Ownership</h2>
            <p>8.1 Intellectual PropertyThe format and content included on the website/application, including logo, graphics, button icons, video, audio, digital data, text, and software is the property of Capvalis and is protected by Indian and international Intellectual & copyright and authors right.<br /><br />All rights are reserved in relation to any trademarks registered and unregistered licensed or owned by Capvalis which exist on the website/application.<br /><br />Website or application or any part of web site/application should not be copied, downloaded or sold or otherwise used for any commercial/Non-commercial purpose without the express written consent of Capvalis.</p>
            <p>8.2 You acknowledge and agree that the website/application, the Services, including without limitation any content available on the website/application and all trademarks, service marks and trade names and other intellectual property rights associated therewith are and will remain, the property of Capvalis and its licensors, as applicable. All content related to Capvalis corporate and business activities embedded in the Application, including any text, graphics, logos, button icons, images, audio clips, and software, is the exclusive property of Capvalis or its licensors and is protected by applicable laws. The compilation (meaning the collection, arrangement, and assembly) of all content on the Application and Services is also the exclusive property of the Capvalis and is protected by applicable laws.</p>
            <p>8.3 All software used on the website/application and the Services is the property of Capvalis or its licensors/software suppliers and protected by Indian and international copyright laws. Any use except as specifically permitted under these Terms, including the reproduction, modification, distribution, transmission, republication, display or performance, of the content on the Application or the Services is strictly prohibited.</p>
            <p>8.4 All Capvalis graphics, logos, and service names are trademarks of the Capvalis or its affiliates. Capvalis trademarks should not be used in connection with any product or service that is not Capvalis, in any manner that is likely to cause confusion among customers, or in any manner that disparages or discredits Capvalis. The logos and trademarks of third parties on the Application belong to respective third parties/brands and Capvalis has no connection whatsoever with such third parties/brands.</p>
        </section>

        {/* Section 9 */}
        <section>
            <h2 className="text-xl font-semibold mb-3 text-green-400">9. Disclaimer of Warranties</h2>
            <p>You expressly acknowledge and agree that, to the maximum extent permitted by applicable law, your use of the application or services is at your sole risk and discretion. the application is licensed to you "as is," "with all faults," and "as available." you bear the risk of using it. Capvalis and/or its affiliates give no express warranties, guarantees, or conditions under or in relation to the application or services. Capvalis and/or its affiliates exclude any implied warranties or conditions, including those of merchantability, fitness for a particular purpose, and non-infringement. Capvalis makes no warranty against and will not be liable or responsible for: (a) interference of your enjoyment of the application or services; (b) losses or damages including any personal injury arising from or in any way related to your access or use of the application and/ or services; (c) use of any content posted, transmitted, or otherwise made available through the application and/ or services; (d) failure, suspension or withdrawal of all or part of the application and/ or any service at any time; (e) any bugs, viruses, or the like which may be transmitted to or through our application or services; (f) functional, uninterrupted, error-free or bug-free delivery of the application and/ or services; (g) security, reliability, or timeliness of the application and/ or services. any content or material downloaded through your use of the application and/ or services is at your own discretion and risk and you will be solely responsible for any damage or loss of data occurring on your device or any other loss or damages of any kind resulting from the download and use of the application and/ or services. no advice, course of conduct or information, whether oral or written, obtained by you from Capvalis or any party or through the application/ or services will create any warranty unless expressly stated in these terms whilst Capvalis will undertake all reasonable efforts and due diligence to ensure security and integrity, Capvalis will, in particular, not be liable for the following: delay or errors in transmission and/ or storage of information to or through Capvalis that might occur from time to time intrusion, distortion, loss or forgery of data, etc., due to act of any third party, failure of any software and/or hardware or telecommunication service provider(s) used by us or any other act beyond our reasonable control. You will be liable for any consequences whatsoever resulting from anything transmitted or caused to be transmitted by you, to or through the application/ or services.</p>
        </section>
        
        {/* Section 10 */}
        <section>
            <h2 className="text-xl font-semibold mb-3 text-green-400">10. Limitation of liability</h2>
            <p>To the maximum extent permitted by applicable laws, under no circumstance will Capvalis or its affiliates, their respective directors, employees, or agents be liable to you or any third party for personal injury, or any special, incidental, indirect, punitive or consequential damages whatsoever, including, but not limited to, damages for loss of profits or revenues, goodwill, failure to transmit or receive any data, loss of confidential information, business interruption, loss of privacy, corruption or loss of data, failure to receive or backup your data (or archived data), for any cause of action, including contract, tort (including negligence) or otherwise and any other loss whatsoever arising out of or in any way arising from or related to the use of Application, or following a failure, suspension or withdrawal of all or part of the Application at any time, any third-party content, software or functions used in connection with the Application even if Capvalis or any or all of its agents have been advised of the possibility of such damages. Notwithstanding anything to the contrary, our maximum aggregate liability to you for any causes whatsoever, and regardless of the form of action (whether liability arises due to negligence or other torts, breach of contract, violation of statute, misrepresentation, or for any other reason), will at all times be limited to the amount paid by you, if any, for using any Services giving rise to the cause of action or Rupees one thousand only (Rs. 1000), whichever is lesser.</p>
        </section>

        {/* Section 11 */}
        <section>
            <h2 className="text-xl font-semibold mb-3 text-green-400">11. Modifications</h2>
            <p>Capvalis reserves the right at any time and from time to time to interrupt, restrict, modify or discontinue, temporarily or permanently, Application (or any part thereof) or any Services without any cause and/or without any notice to you. You agree that Capvalis and its affiliates will not be liable to you or to any third party for any modification, suspension, or discontinuance of the Application or Services.</p>
        </section>

        {/* Section 12 */}
        <section>
            <h2 className="text-xl font-semibold mb-3 text-green-400">12. Indemnification</h2>
            <p>12.1 (meaning Indemnify. v. to guarantee against any loss which another might suffer. For example two parties settle a dispute over a contract, and one of them may agree to pay any claims which may arise from the contract, holding the other harmless).</p>
            <p>12.2 You agree to indemnify, defend and hold harmless Capvalis, its subsidiaries, affiliates and agents and each of their respective officers, directors, employees, successors and assigns from and against any claim, proceeding, loss, damage, liability, cost, demand, or expense (including but not limited to attorney's fees) of any kind arising out of: (i) your access to or use of the website/application and Services; (ii) any breach of these Terms; (iii) your violation of the rights of a third party, including but not limited to infringement of any intellectual property, proprietary right or trade secret of any person or entity, or of any privacy or consumer protection right that is implicated herein; (iv) any violation of law or contractual obligation and any claims, demands, notices pursuant to such violation; (v) your gross negligence or misconduct. These obligations will survive the termination of these Terms.</p>
        </section>

        {/* Section 13 */}
        <section>
            <h2 className="text-xl font-semibold mb-3 text-green-400">13. Force Majeure</h2>
            <p>13.1 (meaning: A Force Majeure clause (French for "superior force") is a contract provision that allows a party to suspend or terminate the performance of its obligations when certain circumstances beyond their control arise, making performance inadvisable, commercially impracticable, illegal, or impossible.) Capvalis will not be liable for any eventuality caused directly or indirectly by any act of God, wars (declared or undeclared), insurrections, acts of terrorism, acts of governments or boycotts, lockouts and other civil unrest, or any act of similar nature beyond Capvalis reasonable control and there will not be a refund due to Force Majeure.</p>
        </section>

        {/* Section 14 */}
        <section>
            <h2 className="text-xl font-semibold mb-3 text-green-400">14. Communication</h2>
            <p>Capvalis may communicate with you through e-mail, SMS, telephone, by posting notifications on the Application (including push notifications) or any other means of communication. By using the Application, you consent to receive such communications from Capvalisin relation to the Application and/or Services, your account information, or any updates/ changes to the Application/ Services and/ or other promotional or marketing communications from Capvalis.</p>
        </section>

        {/* Section 15 */}
        <section>
            <h2 className="text-xl font-semibold mb-3 text-green-400">15. Amendments to this Agreement</h2>
            <p>Please review these terms regularly. We may in our sole discretion modify or amend these Terms from time to time without any prior notice. Your use of the Application or Services upon publication of such modified or amended terms will constitute your deemed acceptance to the modified or amended Terms.</p>
        </section>

        {/* Section 16 */}
        <section>
            <h2 className="text-xl font-semibold mb-3 text-green-400">16. Entire Agreement</h2>
            <p>You agree that these Terms read with the terms of the Privacy Policy and/or any other terms/ policies relating to the Application and/or Services posted by Capvalis on the Application will constitute the complete agreement between you and Capvalis and supersedes any and all proposals, representations or prior agreements, oral or written, and any other communications between you and Capvalis relating to the subject matter of these Terms.</p>
        </section>

        {/* Section 17 */}
        <section>
            <h2 className="text-xl font-semibold mb-3 text-green-400">17. Severability</h2>
            <p>If one or more provisions of these Terms are held to be unenforceable under applicable law(s), the remainder of these Terms will be valid and enforceable.</p>
        </section>

        {/* Section 18 */}
        <section>
            <h2 className="text-xl font-semibold mb-3 text-green-400">18. Waiver</h2>
            <p>If you breach these Terms and Capvalis takes no action, we will still be entitled to use our rights and remedies in any other situation where you breach these Terms.</p>
        </section>

        {/* Section 19 */}
        <section>
            <h2 className="text-xl font-semibold mb-3 text-green-400">19. Right to Takedown</h2>
            <p>You understand and agree that Capvalis may takedown, delete or remove any content available on the Application in its sole discretion, without any notice to you, for any reason whatsoever including on account of your violation of these Terms or if required in accordance with applicable law (including but not limited to the Information Technology Act, 2000).</p>
        </section>

        {/* Section 20 */}
        <section>
            <h2 className="text-xl font-semibold mb-3 text-green-400">20. Platform Services</h2>
            <p>20.1 Your use of Capvalis Platform Services or any part of thereof, is governed by the following terms (“Platform Services Terms”) in addition to the Terms. Platform Services include but are not limited to Journals, Albums, Feeds, Reminders, updates, new events announcements are made available through the website/application.</p>
            <p>20.2 Any capitalized term which has not been defined in these Platform Services Terms shall have the meaning to them in the Capvalis Terms of Service.</p>
        </section>

        {/* Section 21 */}
        <section>
            <h2 className="text-xl font-semibold mb-3 text-green-400">21. Copyright Notice</h2>
            <p>If you believe in good faith that any content displayed or transmitted through the Application infringes your copyright, you may reach us at support@capvalis.com</p>
        </section>

        {/* Section 22 */}
        <section>
            <h2 className="text-xl font-semibold mb-3 text-green-400">22. Variation of the Terms & Conditions, Site, and Service</h2>
            <p>Capvalis reserves the right to modify the Terms and Conditions at any time. In addition, Capvalis may vary or amend or withdraw the Services provided through the Website, the website functionality, and/ or the “look and feel” of the website/application at any time without notice and without liability to its Users.Any modification to the website, Services or Conditions will take effect as soon as such changes are published on the website.Users will be deemed to have accepted any varied Conditions in the event that they use any Services offered through the website following the publication of the varied Conditions.Capvalis does not guarantee the System will be continuously available, error-free; therefore is not responsible for any damage dealt with Users due to such error.The User also agrees that Capvalis is not responsible for any damage caused to their gadgets as a result of using Capvalis website or application.</p>
        </section>

        {/* Section 21 */}
        <section>
            <h2 className="text-xl font-semibold mb-3 text-green-400">23. Governing Law</h2>
            <p>23.1. These Terms are governed by and shall be construed in accordance with the contract law, Information Technology Act 2000, 2008 & further rules & other laws of India without respect to its conflict of laws’ provisions.</p>
            <p>23.2. Disputes, if any, shall be attempted to be resolved amicably. Unresolved disputes shall be to the exclusive jurisdiction of the Courts in Lucknow District.</p>
        </section>
        </div>
        <div className="text-center text-gray-500 text-xs mt-8 pt-4 border-t border-gray-700">
          Last Updated: 30-11-2024 | ©️ 2024 Capvalis
        </div>
      </div>
    </div>
  );
};

export default TermsandCondition;